name: Embedding

on: 
  workflow_dispatch:

jobs:
  embedding:
    runs-on: ubuntu-latest
    steps:
      # 自リポジトリのチェックアウト
      - name: checkout this repository
        uses: actions/checkout@v3

      # PHPファイルのダウンロード
      - run: mkdir -p Temp/artifact
      - name: Download
        run: |
          # アクセストークンの取得
          AUTH_JSON=$(curl -X POST "https://oauth2.googleapis.com/token" \
          -d "client_id=${{ secrets.CLIENT_ID }}" \
          -d "client_secret=${{ secrets.CLIENT_SECRET }}" \
          -d "refresh_token=${{ secrets.REFRESH_TOKEN }}" \
          -d "grant_type=refresh_token")
          TOKEN=$(echo ${AUTH_JSON} | jq .access_token)
          # アーティファクトのダウンロード
          curl "https://www.googleapis.com/drive/v3/files/1-7RpPdsAdUNTPmB6FuMvIj3nDkVseSrx?alt=media" \
          -H "Authorization: Bearer ${TOKEN}" \
          -o Temp/artifact/download_syllabus.tar.xz
      # 展開
      - name: Extract
        run: tar -Jxvf download_syllabus.tar.xz
        working-directory: Temp/artifact

      # 環境構築
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: "3.9"
      - name: Install lib
        run: pip install -r requirements.txt

      # CSVファイルの出力
      # Pythonスクリプト実行
      - name: run
        run: |
          mkdir -p meikoudai_syllaverse/Assets/StreamingAssets/csv
          python syllabus_analysis/embedding.py Temp/artifact meikoudai_syllaverse/Assets/StreamingAssets/csv/feature.csv

      # push
      - name: git config
        run: |
          git config --global user.name GitHub Action
          git config --global user.email action@github.com
      - name: push
        run: |
          git add .
          git commit -m "github actions"
          git push origin ${{ github.ref_name }}
