name: doc2vec

on: 
  workflow_dispatch:

jobs:
  generate-xml:
    runs-on: ubuntu-latest
    steps:
      # 自リポジトリのチェックアウト
      - name: checkout this repository
        uses: actions/checkout@v3
      # syllabus-analysis のリポジトリ
      - run: mkdir -p Temp/syllabus-analysis
      - name: checkout .NET repository
        uses: actions/checkout@v3
        with:
          ref: syllabus-analysis/feature/doc2ve  # テスト用
          path: Temp/syllabus-analysis

      # PHPファイルのダウンロード
      - run: mkdir -p Temp/artifact
      - name: Download
        run: |
          # アクセストークンの取得
          AUTH_JSON=$(curl -X POST "https://oauth2.googleapis.com/token" \
          -d "client_id=${{ secrets.CLIENT_ID }}" \
          -d "client_secret=${{ secrets.CLIENT_SECRET }}" \
          -d "refresh_token=${{ secrets.REFRESH_TOKEN }}" \
          -d "grant_type=refresh_token")
          TOKEN=$(echo ${AUTH_JSON} | jq .access_token)
          # アーティファクトのダウンロード
          curl "https://www.googleapis.com/drive/v3/files/1-7RpPdsAdUNTPmB6FuMvIj3nDkVseSrx?alt=media" \
          -H "Authorization: Bearer ${TOKEN}" \
          -o Temp/artifact/download_syllabus.tar.xz
      # 展開
      - name: Extract
        run: tar -Jxvf download_syllabus.tar.xz
        working-directory: Temp/artifact

      # 環境構築
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: "3.10"
      - name: Install lib
        run: pip install -r requirements.txt

      # CSVファイルの出力
      # モデルのダウンロード
      - name: model download
        run: |
          apt install aria2
          aria2c -x5 -o ./Temp/jawiki.doc2vec.dmpv300d.tar.bz2 https://www.dropbox.com/s/raw/njez3f1pjv9i9xj/jawiki.doc2vec.dmpv300d.tar.bz2
          bzip2 -d ./Temp/jawiki.doc2vec.dmpv300d.tar.bz2
          tar -xvf ./Temp/jawiki.doc2vec.dmpv300d.tar -C ./Temp
      # Pythonスクリプト実行
      - name: run
        run: |
          mkdir -p Assets/StreamingAssets/csv
          python ./Temp/syllabus-analysis/vec2doc.py ./Temp/jawiki.doc2vec.dmpv300d.model ./Temp/artifact ./Assets/StreamingAssets/csv/feature.csv

      # push
      - name: git config
        run: |
          git config --global user.name GitHub Action
          git config --global user.email action@github.com
      - name: push
        run: |
          git add .
          git commit -m "github actions"
          git push origin ${{ github.ref_name }}
